stages:
  data_ingestion: 
    cmd: python src/Asian_African_Elephants_Classification/pipeline/stage_01_data_ingestion.py
    deps:                     
      - src/Asian_African_Elephants_Classification/pipeline/stage_01_data_ingestion.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion/Asian-African-Elephants-Classification_Dataset


  prepare_base_model:
    cmd: python src/Asian_African_Elephants_Classification/pipeline/stage_02_prepare_base_model.py
    deps:
      - src/Asian_African_Elephants_Classification/pipeline/stage_02_prepare_base_model.py
      - config/config.yaml
    params:
      - IMAGE_SIZE
      - INCLUDE_TOP
      - CLASSES
      - WEIGHTS
      - LEARNING_RATE
    outs:
      - artifacts/prepare_base_model



  training:
    cmd: python src/Asian_African_Elephants_Classification/pipeline/stage_03_training.py
    deps:
      - src/Asian_African_Elephants_Classification/pipeline/stage_03_training.py
      - src/Asian_African_Elephants_Classification/components/prepare_callbacks.py
      - config/config.yaml
      - artifacts/data_ingestion/Asian-African-Elephants-Classification_Dataset
      - artifacts/prepare_base_model
    params:
      - IMAGE_SIZE
      - EPOCHS
      - BATCH_SIZE
      - AUGMENTATION
    outs:
      - artifacts/training/model.h5


  

  evaluation:
    cmd: python src/Asian_African_Elephants_Classification/pipeline/stage_04_evaluation.py
    deps:
      - src/Asian_African_Elephants_Classification/pipeline/stage_04_evaluation.py
      - config/config.yaml
      - artifacts/data_ingestion/Asian-African-Elephants-Classification_Dataset
      - artifacts/training/model.h5
    params:
      - IMAGE_SIZE
      - BATCH_SIZE
    metrics:
    - scores.json:
        cache: false