AUGMENTATION: True   # Runtime augmentation
IMAGE_SIZE: [224,224,3] # as per VSG 16 model
BATCH_SIZE: 16  # Training in my local machine
INCLUDE_TOP: False  # Pre-trained model
EPOCHS: 10
CLASSES: 2
WEIGHTS: imagenet  #
LEARNING_RATE: 0.01